# Notifications Package
# This package contains all notification-related configuration

notify:
  # Persistent notifications for important system messages
  - platform: persistent_notification
    name: "system_notifications"

# Input text for custom notification messages
input_text:
  custom_notification:
    name: "Custom Notification Message"
    max: 255
    icon: mdi:message-text

# Automation for custom notifications
automation:
  - id: 'send_custom_notification'
    alias: 'Send Custom Notification'
    description: 'Send a custom notification message'
    trigger:
      - platform: state
        entity_id: input_text.custom_notification
    condition:
      - condition: template
        value_template: "{{ trigger.to_state.state | length > 0 }}"
    action:
      - service: persistent_notification.create
        data:
          message: "{{ states('input_text.custom_notification') }}"
          title: "Custom Message"
          notification_id: "custom_message"
      - service: input_text.set_value
        target:
          entity_id: input_text.custom_notification
        data:
          value: ""
    mode: single
